name: Emaseasy
favicon: null
layout_spectrum: 0.7818168720696121
typography_spectrum: 0.359602693002671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5979733155108988
  lightness: 0.34344423981383443
  saturation: 0.19957798905670643
  rhythmicContrast: 0.33621318102814257
purpose: []
